### ISSUE TITLE
terminal文字选中存在偏移

### ISSUE THREAD

**Issue by FIFCC** [revyos/revyos#11]
在terminal中选中文字时，鼠标指针与实际选中情况存在偏差
镜像版本：20230614

**Comment by FIFCC** [comment]
偏移量大约是横向7像素，纵向7像素（右下鼠标指针）
![B2FC1689-4BC8-4a40-B63C-0698A3755E5E](https://github.com/revyos/revyos/assets/52316103/68987f87-cdcf-4985-b248-58fc42b2ad1f)

**Comment by aiminickwong** [comment]
> 偏移量约是横向7像素，纵向7像素（观测右下鼠标指针） ![B2FC1689-4BC8-4A40-B63C-0698A3755E5E](https://user-images.githubusercontent.com/52316103/252297027-68987f87-cdcf-4985-b248-58fc42b2ad1f.png)

**I also encountered this BUG, ​​has anyone confirmed and responded?**

**Comment by nekorouter** [comment]
This problem is related with hardware cursor render, enable software cursor in X11 can temporary fix this issue.

**Comment by Rabenda** [comment]
https://github.com/revyos/mkimg-th1520/commit/f9867c522485046f1965a3101bd4545520803623
