### ISSUE TITLE
npm ERROR

### ISSUE THREAD

**Issue by FIFCC** [revyos/revyos#12]
操作步骤：
1、安装nodejs和npm（nodejs版本 v18.13.0 npm版本 9.8.1）
2、npm install react -g
3、执行命令 create-react-app riscv-app 命令报错 npm ERR! this[_progress].get(...).finish is not a function

镜像版本：20230614-183009
![微信图片_20230725173745](https://github.com/revyos/revyos/assets/52316103/e08cb5e8-f33e-450f-934b-d81f1f45aaed)
![微信图片_20230725174040](https://github.com/revyos/revyos/assets/52316103/c610ae56-b749-4feb-a6b3-2c8bf26ff1b4)

**Comment by EnfangCui** [comment]
该问题在20231214镜像版本中已经解决。
npm install react -g
npm install create-react-app -g
再用create-react-app创建自己的app即可。
（我的测试环境为LicheePi4A）

**Comment by FIFCC** [comment]
该问题在20240202镜像版本中已经解决，此issue关闭
