### ISSUE TITLE
[需求]: backport 部分补丁到gcc13.2

### ISSUE THREAD

**Issue by Rabenda** [revyos/revyos#20]
目标分支:
https://github.com/revyos/gcc/tree/revyos-gcc13.2

需要backport的补丁:
https://github.com/gcc-mirror/gcc/commit/0e25761b373f075a41d43b9462366a653dbf1121
https://github.com/gcc-mirror/gcc/commit/d8bdc978dc9cd4a6210997edacedb954375af70d

**Comment by pz9115** [comment]
已解决冲突，提交到PR：https://github.com/revyos/gcc/pull/3

**Comment by Rabenda** [comment]
验收通过
