### ISSUE TITLE
Device tree not found or missing FDT support after kernel upgrade

### ISSUE THREAD

**Issue by bgklc** [revyos/revyos#23]
I use LPI4A_20230912.zip on lichee pi 4a
After apt full-upgrade u-boot says

Device tree not found or missing FDT support

and does not boot further

I need to reflash the image.

Thanks! I can provide further details if needed.

**Comment by bgklc** [comment]
After flashing https://mirror.iscas.ac.cn/revyos/extra/images/lpi4a/20230916/ apt full upgrade and reboot succeeds.

**Comment by Rabenda** [comment]
The problem has been solved. Close the issue.
