### ISSUE TITLE
文档存在错误

### ISSUE THREAD

**Issue by KiritakeKumi** [revyos/revyos#29]
问题文档链接：
https://github.com/revyos/revyos/blob/main/Build/%E6%89%8B%E5%8A%A8%E7%BC%96%E8%AF%91%E5%86%85%E6%A0%B8(Manually%20compile%20the%20kernel).md

问题1：
在“编译内核：”小节中
sudo make CROSS_COMPILE=riscv64-unknown-linux-gnu- ARCH=riscv INSTALL_PATH=../rootfs/boot **zinstall** -j$(nproc)

这个 **z**install 是否应为 install

问题2：
在“编译内核：”小节中
sudo cp -v arch/riscv/boot/dts/thead/light-lpi4a.dtb ../rootfs/boot/
sudo cp -v arch/riscv/boot/dts/thead/light-lpi4a-dsi0-hdmi.dtb ../rootfs/boot/

这两个dtb文件均已不存在 目测已经被
[light-lpi4a-cluster-16gb.dts](https://github.com/revyos/thead-kernel/blob/lpi4a/arch/riscv/boot/dts/thead/light-lpi4a-cluster-16gb.dts)
[light-lpi4a-cluster.dts](https://github.com/revyos/thead-kernel/blob/lpi4a/arch/riscv/boot/dts/thead/light-lpi4a-cluster.dts)
所替代 但是文档没有更新？

**Comment by Rabenda** [comment]
cluster是cluster的设备树 没有替代 但是文档现在是错误待修正

zinstall失效原因是7月的提交导致 因为在uboot+extlinux 无法对压缩内核进行引导 原因还没有查证
https://github.com/revyos/thead-kernel/commit/0683ead84165591247c46e7f186cca1909eaebb2
