### ISSUE TITLE
装工具链时，经常系统卡死

### ISSUE THREAD

**Issue by ZhangYiXiSucceed** [revyos/revyos#30]
<img width="699" alt="0ef04a50556ed3ca3115cf0fcf14ac77" src="https://github.com/revyos/revyos/assets/43594130/7a0a9962-3016-4ff1-b326-9b2480ff95ff">
<img width="732" alt="caf00b2fa11cd59fa79a435c4aa8000f" src="https://github.com/revyos/revyos/assets/43594130/c0ce4979-4a30-468d-9726-f25bc79e42d1">

**Comment by ZhangYiXiSucceed** [comment]
装着装着系统，就不动了，然后按什么都反映，两次了，都是后面，后面重试几次才行

**Comment by Rabenda** [comment]
请按以下次序检查相关问题
- 是否为 2GHz 设备树
  - 使用 2GHz 设备树需要自己保证机器的稳定性 系统不保证这种情况下可用性
- 系统是否有问题
  - 推荐重新刷写最新的镜像 旧版镜像可能存在稳定性问题

**Comment by RevySR** [comment]
长时间无回应 关闭
