### ISSUE TITLE
[需求] 分析当前X11桌面性能热点

### ISSUE THREAD

**Issue by RevySR** [revyos/revyos#33]
现状是整个界面实际上处于一种不跟手的状态
需要分析原因

**Comment by Icenowy** [comment]
使用 xdotool 模拟在 panel 菜单上移动鼠标的负载时：
![图片](https://github.com/revyos/revyos/assets/1916518/98106501-56e0-4992-aa87-1b77d3250f4f)
htop 显示，此时 Xorg + xfce4-panel 合计占用 100% CPU ，其中 Xorg 占据超过 50%

`perf-thead top -p ${XORG_PID}` 显示

**Comment by Icenowy** [comment]
拿到调试符号之后，发现热点在 FBOAttachableHasBeenModified 里（这个函数本身占了 26% 的总 CPU 时间），疑似与 Glamor 实现显示到 GBM buffer 的方式有关。

**Comment by RevySR** [comment]
鼠标问题已经解决
