### ISSUE TITLE
MIPI 屏幕无法在 xfce 中调节亮度

### ISSUE THREAD

**Issue by wu-yue-yu** [revyos/revyos#40]
预期行为是，通过 power manager 可以直接调节 MIPI 屏幕亮度。
首先在设置菜单中打开 power manager 设置菜单

![step_1](https://github.com/revyos/revyos/assets/59756623/4fc4df52-1dce-4b89-8eb2-62220179720f)

然后打开最下方的 System tray icon 使任务栏图标显示

![step_2](https://github.com/revyos/revyos/assets/59756623/d793e40e-b3aa-462a-922e-a3bc3acce2e0)

然后右键桌面右上角的电池图标可以看到亮度的设置条，预期这里应该能调节亮度

![step_3](https://github.com/revyos/revyos/assets/59756623/8dcfbc97-a0ed-47d2-9c32-8c56427028ca)

现象：目前的 revyos 最新版本 xfce 仍然不能调节亮度，在 yocto 1.2.1 SDK 中测试能够在 xfce 桌面调节亮度

**Comment by nekorouter** [comment]
缺少pkexec导致的
修复见以下链接
https://github.com/revyos/mkimg-th1520/commit/971294434e8c24a880d10a4ec72c03bb540ef92d#diff-22b01609e50b9a5519ee7fa7b7e7c8ad6de8dc57dbebeea9e9217a27f85c4097
