### ISSUE TITLE
mmc status get /dev/mmcblk1   ioctl: Connection timed out

### ISSUE THREAD

**Issue by atzlinux** [revyos/revyos#44]
uname -a
Linux lpi4a 5.10.113-lpi4a #2023.10.24.02.18+3e042d29a SMP PREEMPT Tue Oct 24 02:19:10 UTC  riscv64 GNU/Linux

apt install mmc-utils

mmc 命令无法读取 256G SD 卡信息：

mmc status get /dev/mmcblk1
ioctl: Connection timed out
Could not read response to SEND_STATUS from /dev/mmcblk1

dmesg 有错误信息：
[四 12月  7 16:59:56 2023] sdhci-dwcmshc ffe7090000.sd: __mmc_blk_ioctl_cmd: cmd error -110
[四 12月  7 17:00:13 2023] sdhci-dwcmshc ffe7090000.sd: __mmc_blk_ioctl_cmd: cmd error -110

256G  SD 卡信息：
fdisk -l
Disk /dev/mmcblk1: 230.47 GiB, 247463936000 bytes, 483328000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x2d0952a9

Device         Boot Start       End   Sectors   Size Id Type
/dev/mmcblk1p1       2048 483327999 483325952 230.5G 83 Linux

**Comment by weilinfox** [comment]
换张 SD 卡试试？可能荔枝派 4A 挑卡了

**Comment by atzlinux** [comment]
在荔枝派上运行：
```
mmc status get /dev/mmcblk0
SEND_STATUS response: 0x00000900
DEVICE STATE: TRANS
STATUS: READY_FOR_DATA
```
可以获取其 8GB mmc 存储的信息，dmesg 也没有报错。
mmc 命令应该是只能够用于 mmc 存储介质，不适用于 SD 卡。

这个 issue 我先关闭吧。
