### ISSUE TITLE
Statement of the underflow problem of Xuantie C910 (by XuanTie Group)

### ISSUE THREAD

**Issue by 202459768** [revyos/revyos#47]
Statement of the underflow problem of Xuantie C910 (by XuanTie Group)

**Description of the issue**

For RISC-V floating-point arithmetic instructions, tininess is detected after rounding as the exponent range is unbounded. Xuantie C910 uses bounded exponent to judge underflow exceptions, resulting in the following extreme cases where underflow bit may not be set:
● The exponent of the original result is emin-1(single precision is -127, double precision is -1024)
● The first N bits of the mantissa of the original result are all 1 (single precision is 24, double precision is 53)
Taking single precision as an example, if the original calculation result is:
![image](https://github.com/revyos/revyos/assets/117722273/817560b6-697f-428d-a242-7698171ca154)
According to the rounding mode (round to even) , the above results will not be rounded, resulting in an underflow exception.However, Xuantie C910 rounds the above results according to the following format, so there will be no underflow exception.
2-126x0.11111111111111111111111100001…0000
If the original calculation results do not satisfy the extreme corner scenario described above, the underflow exception can be correctly identified.

**Impact of the issue**

On multiplication, division and conversion instructions(narrow conversion), Xuantie C910 will miss the underflow flag only when the corner result is presented, but will still get the result consistent with correct behaviour.
At the same time, RISC-V floating-point operation exceptions only affect the underflow bit FFLAGS, not the trap. FFLAGS is an accumulative flag. If it is not the only underflow calculation in the whole program, the final calculation result and the underflow flag bit will be correct.
Therefore, in practice, the impact of this issue is expected to be very limited.

_Originally posted by @QJtaibai in https://github.com/revyos/revyos/issues/17#issuecomment-1865370138_

**Comment by RevySR** [comment]
duplicate #17
