### ISSUE TITLE
Trying to run KVM on Lpi4a / Revyos results in: ERROR    internal error: process exited while connecting to monitor: ... qemu-system-riscv64: kvm_init_vcpu: kvm_arch_init_vcpu failed (0): Bad address

### ISSUE THREAD

**Issue by pascal71** [revyos/revyos#52]
Good afternoon all,

Best wishes for the new year.

When trying to run KVM with Archlinux cloud-init image for riscv64 using virt-install, I run into the error:

ERROR    internal error: process exited while connecting to monitor: 2024-01-13T15:24:36.513851Z qemu-system-riscv64: kvm_init_vcpu: kvm_arch_init_vcpu failed (0): Bad address

Command used:

virt-install \
--name kvmlpt30-n05 \
--ram 4096 \
--vcpus 2 \
--os-variant archlinux \
--import \
--disk path=/var/lib/libvirt/images/kvmlpt30-n05.img,format=qcow2,bus=virtio \
--disk path=/var/lib/libvirt/images/user-data-n05.img,device=cdrom \
--network bridge:virbr0,model=virtio \
--noautoconsole

/usr/sbin/kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

Suggests that KVM accel is supported?

Is Virtualization supported on this platform (H extension on T-HEAD) and on RevyOS/kernel?

If you need help, kindly let me know.

Thanks in advance.

Kind regards,

   Pascal van Dam

**Comment by RevySR** [comment]
not support.
