### ISSUE TITLE
Upgrade mesa to 23.x

### ISSUE THREAD

**Issue by ksco** [revyos/revyos#56]
The current mesa version on revyos-pioneer is 22.3.6. But box64 + wine 9.x wow64 + dxvk does not work properly, maybe the mesa version is too old.

dxvk support is necessary for essentially any Win32 games to be playable on SG2042 as wow64 OpenGL has very bad performance (worse than soft renderer).

Related: #35

**Comment by RevySR** [comment]
Merged.
