### ISSUE TITLE
What to do when cpu doesn't have v-extension

### ISSUE THREAD

**Issue by predator2k** [revyos/revyos#59]
I want to try this on C906fd. Is this possible or not supported at all? What part should I modify (kernel or just the compiling stuff)? 

Looking forward to your reply.

**Comment by nekorouter** [comment]
What hardware/chip do you mean "C906fd"?

**Comment by predator2k** [comment]
It's https://github.com/T-head-Semi/openc906 running on FPGA actually

**Comment by nekorouter** [comment]
The implementation of this soft core has no v-extension support, unfortunately you need to realize this part on your own.

**Comment by predator2k** [comment]
So this OS heavily depends on V-extension?

**Comment by nekorouter** [comment]
Actually no, we have both kernel and software that enabled vector support or not, but revyos's kernel and software are mainly work on real hardware (TH1520), we are not sure if those can run on openc906...

**Comment by predator2k** [comment]
So the issues are more of soc stuff(IO, device tree, etc.), and OS's V-extension dependence can probably be turned-off without too much impact?

**Comment by nekorouter** [comment]
That should be correct, though we didn't tested on openc906 so no guarantee to work.

**Comment by predator2k** [comment]
ok
