### ISSUE TITLE
exfat文件系统不支持

### ISSUE THREAD

**Issue by FIFCC** [revyos/revyos#6]
![6（exfat文件系统不支持）](https://github.com/revyos/revyos/assets/52316103/aad22e63-4b41-40cd-9022-b4710ceb3d86)

**Comment by nekorouter** [comment]
解决方法：
1. 内核中打开CONFIG_EXFAT_FS
2. 预装exfatprogs

**Comment by Rabenda** [comment]
https://github.com/revyos/thead-kernel/pull/11
