### ISSUE TITLE
移植kernel，无法打开 /dev/console

### ISSUE THREAD

**Issue by h-dxgfx** [revyos/revyos#60]
请教关于kernel移植中遇到的问题。
详情可见：
https://maixhub.com/discussion/100179
使用linux-5.10.4源码：https://github.com/c-sky/csky-linux/archive/5b8e01b571c961a52a0e24134f9f916ddfdb7a2e.tar.gz

**Comment by RevySR** [comment]
CONFIG_SERIAL_8250 是需要builtin的

**Comment by RevySR** [comment]
solved.
