### ISSUE TITLE
glibc: 同步T-Head工具链 2.8.0修改

### ISSUE THREAD

**Issue by RevySR** [revyos/revyos#61]
现在缺少这两个补丁没有同步

https://github.com/T-head-Semi/glibc/commit/31597b26be331194034bd65925d4ea0a3c682911
https://github.com/T-head-Semi/glibc/commit/a04c0ab829b9a2a9afe677c3af5a0a6ac65a8b09

同步的目标branch
https://github.com/revyos/glibc/tree/revyos-2.36

**Comment by pz9115** [comment]
WIP

**Comment by pz9115** [comment]
https://github.com/revyos/glibc/pull/2
