### ISSUE TITLE
sdk 1.5.4 升级计划

### ISSUE THREAD

**Issue by RevySR** [revyos/revyos#65]
SDK 版本发布之后需要检查如下功能升级
- [x] thead-kernel
  - [x] gpu_bxm_4_64-kernel
  - [x] vpu-vc8000e-kernel
  - [x] vpu-vc8000d-kernel
  - [x] npu-ax3386-kernel
  - [x] thead-ddr-pmu
- [x] thead-uboot
- [x] thead-opensbi
- [x] lowpower
- [x] th1520-boot-firmware
  - [x] thead-opensbi 二进制同步
  - [x] str - lowpower 二进制同步
  - [x] aon 二进制同步
  - [x] audio 二进制同步
- [x] th1520-npu
  - [x] 二进制库更新
- [x] thead-gles-addons
  - [x] 二进制库更新
- [x] th1520-peripheral-firmware
  - [x] 8723ds 网卡/蓝牙/用户态 二进制
  - [x] aic8800 网卡/蓝牙/用户态 二进制
- [x] 音频编解码 - omx
  - [x] gsteamer-omx
  - [x] ffmpeg-omx
  - [x] th1520-vpu omx 二进制

**Comment by KevinMX** [comment]
lpi4a 16G 3.5mm 音频输出异常
