### ISSUE TITLE
Failed to write rootfs on 8GB emmc lpi4a board

### ISSUE THREAD

**Issue by B1ACK917** [revyos/revyos#67]
Failed to write [root-lpi4a-20240601_180941.ext4.zst](https://mirror.iscas.ac.cn/revyos/extra/images/lpi4a/20240601/root-lpi4a-20240601_180941.ext4.zst) to 8GB emmc lpi4a board.

-------------log start--------------
$ sudo ./fastboot flash root root-lpi4a-20240601_180941.ext4
Sending sparse 'root' 1/31 (109228 KB)             OKAY [  2.823s]
Writing 'root'                                     OKAY [  5.660s]
Sending sparse 'root' 2/31 (114684 KB)             OKAY [  2.970s]
Writing 'root'                                     OKAY [  2.623s]
Sending sparse 'root' 3/31 (114684 KB)             OKAY [  2.998s]
Writing 'root'                                     OKAY [  2.657s]
Sending sparse 'root' 4/31 (101392 KB)             OKAY [  2.648s]
Writing 'root'                                     OKAY [  2.592s]
Sending sparse 'root' 5/31 (114684 KB)             OKAY [  3.014s]
Writing 'root'                                     OKAY [  2.604s]
Sending sparse 'root' 6/31 (114681 KB)             OKAY [  2.995s]
Writing 'root'                                     OKAY [  2.743s]
Sending sparse 'root' 7/31 (114360 KB)             OKAY [  2.969s]
Writing 'root'                                     OKAY [  3.139s]
Sending sparse 'root' 8/31 (104013 KB)             OKAY [  2.727s]
Writing 'root'                                     OKAY [  4.551s]
Sending sparse 'root' 9/31 (100860 KB)             OKAY [  2.607s]
Writing 'root'                                     OKAY [  2.286s]
Sending sparse 'root' 10/31 (114684 KB)            OKAY [  2.956s]
Writing 'root'                                     OKAY [  2.610s]
Sending sparse 'root' 11/31 (114684 KB)            OKAY [  2.948s]
Writing 'root'                                     OKAY [  2.671s]
Sending sparse 'root' 12/31 (112132 KB)            OKAY [  2.857s]
Writing 'root'                                     OKAY [  2.495s]
Sending sparse 'root' 13/31 (114684 KB)            OKAY [  2.984s]
Writing 'root'                                     OKAY [  2.595s]
Sending sparse 'root' 14/31 (109894 KB)            OKAY [  2.845s]
Writing 'root'                                     OKAY [  2.958s]
Sending sparse 'root' 15/31 (114001 KB)            OKAY [  2.944s]
Writing 'root'                                     OKAY [  2.926s]
Sending sparse 'root' 16/31 (103209 KB)            OKAY [  2.672s]
Writing 'root'                                     OKAY [  3.296s]
Sending sparse 'root' 17/31 (114461 KB)            OKAY [  2.958s]
Writing 'root'                                     OKAY [  2.833s]
Sending sparse 'root' 18/31 (111617 KB)            OKAY [  2.859s]
Writing 'root'                                     OKAY [  3.404s]
Sending sparse 'root' 19/31 (110843 KB)            OKAY [  2.842s]
Writing 'root'                                     OKAY [  2.900s]
Sending sparse 'root' 20/31 (111656 KB)            OKAY [  2.874s]
Writing 'root'                                     OKAY [  2.600s]
Sending sparse 'root' 21/31 (114684 KB)            OKAY [  2.958s]
Writing 'root'                                     OKAY [  2.580s]
Sending sparse 'root' 22/31 (114260 KB)            OKAY [  2.963s]
Writing 'root'                                     OKAY [  2.549s]
Sending sparse 'root' 23/31 (114333 KB)            OKAY [  2.945s]
Writing 'root'                                     OKAY [  2.776s]
Sending sparse 'root' 24/31 (108277 KB)            OKAY [  2.791s]
Writing 'root'                                     FAILED (remote: 'Request would exceed partition size!')
fastboot: error: Command failed

Any idea on this?

**Comment by RevySR** [comment]
8G emmc is not supported.
