### ISSUE TITLE
meles 蓝牙连接错误

### ISSUE THREAD

**Issue by Sebastianhayashi** [revyos/revyos#71]
根据[文档](https://milkv.io/zh/docs/meles/os-usage/revyos#%E8%93%9D%E7%89%99%E8%BF%9E%E6%8E%A5)中的“蓝牙连接”教程
问题：无法找到 brcm_patchram_plus 包
 
![image](https://github.com/revyos/revyos/assets/172239551/60b4b6c7-3ee4-472a-bd31-cc4ba284952d)

**Comment by FIFCC** [comment]
根据[参考文章](https://milkv.io/zh/docs/meles/os-usage/revyos#%E8%93%9D%E7%89%99%E8%BF%9E%E6%8E%A5)中所写

下载此文件[brcm_patchram_plus.zip](https://github.com/user-attachments/files/16231286/brcm_patchram_plus.zip)，存放在/home/debian/下

将 vi bt_enable.sh 中的内容改为

'''
echo 445 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio445/direction
echo 0 > /sys/class/gpio/gpio445/value
sleep 2
echo 1 > /sys/class/gpio/gpio445/value
sleep 1

/home/debian/brcm_patchram_plus --enable_hci --no2bytes --tosleep 200000 --baudrate 115200 --patchram  /lib/firmware/brcm/BCM4345C5.hcd /dev/ttyS4 &
'''

随后执行bt_enable.sh脚本即可
