### ISSUE TITLE
Usb键盘输入存在延迟

### ISSUE THREAD

**Issue by FIFCC** [revyos/revyos#9]

**Comment by atzlinux** [comment]
通过 ssh 远程连接输入没有问题，USB 物理键盘连接输入，在 Xfce 和 切换到终端的情况下，键盘输入卡顿非常明显。

**Comment by Rabenda** [comment]
https://github.com/revyos/thead-kernel/commit/f158bc369fc3350e070d3c06a75a0fc56f8e7dfe
已修复
